version: "3.8"
services:
  web:
    container_name: server
    build:
      context: ./
      dockerfile: ./apps/server/Dockerfile
    command: npm run --prod
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
